#               ########################
#               ## Spawn Proof Blocks ##
#               ########################

# The list below contains the default values
# for the spawn proof blocks (i.e. synthetic blocks)

# If altering is required add or remove the block name 
# to the following list.

# Wildcards (*) can be used.
# Adding an wildcard will automatically add any block
# that has that string on its name.

spawnproof-blocks:
- polished_*
- smooth_stone
- iron_block
- redstone_*
- diamond_block
- coal_block
- emerald_block
- _concrete_powder*
- _concrete*

#               ###########################
#               ## Register Legacy Types ##
#               ###########################

# Legacy types SHOULDN'T be registered
# ##########################################
# ### UNLESS YOU KNOW WHAT YOU ARE DOING ###
# ##########################################
# DON'T change this flag unless you are CERTAIN.

register-legacy: false
